data:
  tokenizer_path: "./models/tokenizer-clean.json"
  train_path: "./corpus_split/train.txt"
  eval_path: "./corpus_split/val.txt"
  seq_length: 128
  eval_samples: 8192

model:
  type: "GPTJ" # or "GPT2"
  name: "GPTJ-705M"
  hidden_size: 1536
  intermediate_size: 3072 # train.py uses default = 4 * hidden_size 
  n_layer: 24
  n_head: 16 # Change this if you're using GPT2
  tie_word_embeddings: True

training:
  lr: 2.5e-4
  batch_size: 128
  num_epochs: 4
  gradient_accumulation_steps: 16
  warmup_steps: 300
  fp16: True

logging: 
  output_dir: "./models/"

