data:
  tokenizer_path: "./models/tokenizer-clean.json"
  train_path: "./cosrpus_split/train"
  eval_path: "./corpus_split/val"
  seq_length: 128
  eval_samples: 8192

model:
  type: "Llama" # or "GPT2"
  name: "Llama-360M"
  hidden_size: 1024
  intermediate_size: 3072
  n_layer: 24
  n_head: 8 # Change this if you're using GPT2

training:
  lr: 3e-4
  batch_size: 128
  num_epochs: 4
  gradient_accumulation_steps: 8
  warmup_steps: 300
  fp16: True

logging: 
  output_dir: "./models/"

